version: '3'
services:
  socialtodo:
    build: .
    ports:
    - "8080:8080"
    env_file:
    - ../secrets.env
    links:
    - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: dolphins
